name: Craftalot
version: '${project.version}'
main: me.chazzagram.craftalot.Craftalot
api-version: '1.20'
authors: [Chazzagram]
description: Craftalot game mode plugin.
commands:
  craftalot:
    description: Main craftalot command.
    usage: /<command>
    permission: craftalot.admin
    permission-message: You don't have permission to run this command.
    aliases:
      - ca