spawn:
  x: 0
  y: 0
  z: 0
spawnOnJoin: 'true'

# ------ Craftalot Config ------
craftalot:

  # Set how long the game will last for in seconds.
  # Default: 600 (10 minutes)
  time-limit-in-seconds: 600

  # Set where players will be teleported before the game begins.
  # This feature is set in-game using /ca gui.
  lobby-location:
    x: 0
    y: 0
    z: 0
    world: world

  # Set where players will be teleported when the game begins.
  # This feature is set in-game using /ca gui.
  game-begin-location:
    x: 0
    y: 0
    z: 0
    world: world

  # Configuration location for the Edguard entity.
  # It is recommended to leave this setting unchanged.
  # Use '/ca edguard' in-game to modify Edguard's properties.
  edguard-location:
    x: 0
    y: 0
    z: 0
    world: world

  # Set the time of day which the game will be played in.
  # Syntax (day, night)
  # Default: day
  time-of-day: day

  # Whether players are visible to each other while playing.
  # Syntax (true, false)
  # Default: true
  player-visibility: true

  # Point system configuration
  points:

    # Enable/Disable points.
    # Syntax (true, false)
    # Default: true
    enabled: true

    # Points per item crafted.
    # Default: 1
    per-craft: 1
