name: Craftalot
version: 'PREBUILD-24.0216'
main: me.chazzagram.craftalot.Craftalot
api-version: '1.20'
authors: [Chazzagram]
description: Craftalot game mode plugin.
commands:
  die:
    description: A simple command to kill yourself.
    usage: /<command>
    permission: lj.die
    permission-message: You don't have permission to run this command.
  craftalot:
    description: Main craftalot command.
    usage: /<command>
    permission: craftalot.admin
    permission-message: You don't have permission to run this command.
    aliases:
      - ca
  setspawn:
    description: A simple command to set world spawnpoint.
    usage: /<command>
    permission: lj.setspawn
    permission-message: You don't have permission to run this command.
  spawnonjoin:
    description: Toggle teleporting player to spawn on join.
    usage: /<command>
    permission: lj.spawnonjoin
    permission-message: You don't have permission to run this command.
  spawn:
    description: Teleport to spawn.
    usage: /<command>
    permission: lj.spawn
    permission-message: You don't have permission to run this command.
  god:
    description: Give yourself invulnerability.
    usage: /<command>
    permission: lj.god
    permission-message: You don't have permission to run this command.
    aliases:
      - godmode
      - invincible
      - invulnerable
  repeat:
    description: Repeat stuff back to you.
permissions:
  ld.die:
    description: Allows the user to use /die.